/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import modelos.classes.Movimentacao;
import modelos.classes.TipoDeDespesa;
import modelos.classes.Veiculo;
import persistencia.MovimentacaoDAO;
import persistencia.TipoDeDespesasDAO;
import persistencia.VeiculosDAO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;


/**
 *
 * @author narut
 */
public class TelaDeMovimentacao extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaDeMovimentacao.class.getName());
  private MovimentacaoDAO movDao = new MovimentacaoDAO();
  private VeiculosDAO veicDao = new VeiculosDAO();
  private TipoDeDespesasDAO tipoDao = new TipoDeDespesasDAO();

  private String modo = ""; // "" | "CADASTRAR" | "EDITAR" | "CONSULTAR"

  public TelaDeMovimentacao() {
    initComponents();
    this.setLocationRelativeTo(null);

    carregarTabela();
    carregarComboDespesas();
    bloquearCampos();
  }

  private void carregarComboDespesas() {
    try {
      jComboBoxDespesa.removeAllItems();
      jComboBoxDespesa.addItem("Selecione...");

      ArrayList<TipoDeDespesa> lista = tipoDao.listaDeTiposDeDespesas();
      for (TipoDeDespesa t : lista) {
        jComboBoxDespesa.addItem(t.getDescricao());
      }
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, "Erro ao carregar despesas: " + e.getMessage());
    }
  }

  private int gerarProximoId() {
    try {
      ArrayList<Movimentacao> lista = movDao.listagemDeMovimentacoes();
      int maxId = 0;
      for (Movimentacao m : lista) {
        if (m.getIdMovimentacao() > maxId) {
          maxId = m.getIdMovimentacao();
        }
      }
      return maxId + 1;
    } catch (Exception e) {
      return 1;
    }
  }

  private void bloquearCampos() {
    jTextFieldMovimentacao.setEditable(false);
    jTextFieldveiculos.setEditable(false);
    jComboBoxDespesa.setEnabled(false);
    jTextFieldData.setEditable(false);
    jTextFieldValor.setEditable(false);
    jTextFieldDescricao.setEditable(false);
    jComboBoxStatus.setEnabled(false);
  }

  private void liberarCampos() {
    jTextFieldMovimentacao.setEditable(false);
    jTextFieldveiculos.setEditable(true);
    jComboBoxDespesa.setEnabled(true);
    jTextFieldData.setEditable(true);
    jTextFieldValor.setEditable(true);
    jTextFieldDescricao.setEditable(true);
    jComboBoxStatus.setEnabled(true);
  }

  private void limparCampos() {
    jTextFieldMovimentacao.setText("");
    jTextFieldveiculos.setText("");
    if (jComboBoxDespesa.getItemCount() > 0) jComboBoxDespesa.setSelectedIndex(0);
    jTextFieldData.setText("");
    jTextFieldValor.setText("");
    jTextFieldDescricao.setText("");
    jComboBoxStatus.setSelectedIndex(0);
  }

  private void carregarTabela() {
    try {
      DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
      modelo.setRowCount(0);

      ArrayList<Movimentacao> lista = movDao.listagemDeMovimentacoes();
      for (Movimentacao m : lista) {
        String nomeVeiculo = "";
        try {
          Veiculo v = veicDao.buscarPorId(m.getIdVeiculo());
          if (v != null) nomeVeiculo = v.getMarca() + " " + v.getModelo();
        } catch (Exception e) {
          nomeVeiculo = "(erro ao carregar veículo)";
        }

        String nomeDespesa = "";
        try {
          TipoDeDespesa t = tipoDao.buscarPorId(m.getIdTipoDespesa());
          if (t != null) nomeDespesa = t.getDescricao();
        } catch (Exception e) {
          nomeDespesa = "(erro ao carregar despesa)";
        }

        String status = "";
        try {
          Object s = null;
          try {
            s = m.getStatus(); // espera String ou algo similar
          } catch (NoSuchMethodError | Exception ignore) {
            s = null;
          }
          status = (s == null) ? "" : String.valueOf(s);
        } catch (Exception ex) {
          status = "";
        }

        modelo.addRow(new Object[]{
          m.getIdVeiculo(),
          m.getIdTipoDespesa(),
          m.getIdMovimentacao(),
          nomeVeiculo,
          nomeDespesa,
          m.getData(),
          m.getValor(),
          m.getDescricao(),
          status
        });
      }
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());

    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jEditorPane1 = new javax.swing.JEditorPane();
    jScrollBar1 = new javax.swing.JScrollBar();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jButtonVoltar = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jComboBoxDespesa = new javax.swing.JComboBox<>();
    jButtonCadastrarMovimentacao = new javax.swing.JButton();
    jTextFieldveiculos = new javax.swing.JTextField();
    jTextFieldMovimentacao = new javax.swing.JTextField();
    jTextFieldData = new javax.swing.JTextField();
    jTextFieldValor = new javax.swing.JTextField();
    jTextFieldDescricao = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jButtonGerenciarMovimentacao = new javax.swing.JButton();
    jButtonRemoverMovimentacao = new javax.swing.JButton();
    jButtonConfirmar = new javax.swing.JButton();
    jComboBoxStatus = new javax.swing.JComboBox<>();
    jLabel9 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();

    jScrollPane1.setViewportView(jEditorPane1);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(31, 146, 126));

    jPanel2.setBackground(new java.awt.Color(16, 58, 83));

    jButtonVoltar.setBackground(new java.awt.Color(16, 58, 83));
    jButtonVoltar.setForeground(new java.awt.Color(16, 58, 83));
    jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/botao-voltar.png"))); // NOI18N
    jButtonVoltar.setBorder(null);
    jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonVoltarActionPerformed(evt);
      }
    });

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object[][]{
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null}
      },
      new String[]{
        "ID Veiculo", "ID Despesa", "ID Movimentação", "Veiculo", "Despesa", "Data", "Valor", "Descrição", "Status"
      }
    ));
    jScrollPane2.setViewportView(jTable1);

    jButtonCadastrarMovimentacao.setText("Cadastrar Movimentação");
    jButtonCadastrarMovimentacao.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCadastrarMovimentacaoActionPerformed(evt);
      }
    });

    jTextFieldveiculos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldveiculosActionPerformed(evt);
      }
    });

    jTextFieldMovimentacao.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldMovimentacaoActionPerformed(evt);
      }
    });

    jTextFieldData.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldDataActionPerformed(evt);
      }
    });

    jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldValorActionPerformed(evt);
      }
    });

    jTextFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldDescricaoActionPerformed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("ID Veiculo");

    jLabel4.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("ID Movimentação");

    jLabel5.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("ID Despesa");

    jLabel6.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Data");

    jLabel7.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("Valor");

    jLabel8.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("Descrição");

    jButtonGerenciarMovimentacao.setText("Gerenciar Movimentação");
    jButtonGerenciarMovimentacao.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonGerenciarMovimentacaoActionPerformed(evt);
      }
    });

    jButtonRemoverMovimentacao.setText("Remover Movimentação");
    jButtonRemoverMovimentacao.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonRemoverMovimentacaoActionPerformed(evt);
      }
    });

    jButtonConfirmar.setText("Confirmar");
    jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonConfirmarActionPerformed(evt);
      }
    });

    jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Ativa", "Finalizada"}));

    jLabel9.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(255, 255, 255));
    jLabel9.setText("Status");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addGap(24, 24, 24)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addComponent(jButtonCadastrarMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(29, 29, 29)
              .addComponent(jButtonGerenciarMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(18, 18, 18)
              .addComponent(jButtonRemoverMovimentacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jButtonVoltar)
              .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3)
                .addComponent(jTextFieldveiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(jTextFieldDescricao)
                  .addComponent(jComboBoxDespesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jTextFieldMovimentacao, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                  .addComponent(jTextFieldData, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                  .addComponent(jTextFieldValor, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addComponent(jLabel5)
                .addComponent(jLabel6)
                .addComponent(jLabel7)
                .addComponent(jLabel8)
                .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel9))
              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addGap(91, 91, 91)
              .addComponent(jLabel3)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jTextFieldveiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(7, 7, 7)
              .addComponent(jLabel5)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jComboBoxDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(13, 13, 13)
              .addComponent(jLabel4)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jTextFieldMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(18, 18, 18)
              .addComponent(jLabel6)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addComponent(jLabel7)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(18, 18, 18)
              .addComponent(jLabel8)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel9)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(18, 18, 18)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonVoltar)))
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addGap(41, 41, 41)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonCadastrarMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonGerenciarMovimentacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRemoverMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(30, 30, 30)))
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabel1.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
    jLabel1.setText("controle de frotas");

    jLabel2.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
    jLabel2.setText("GYNLOG");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(jLabel2)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 640, Short.MAX_VALUE)
          .addComponent(jLabel1)
          .addGap(19, 19, 19))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
              .addGap(12, 12, 12)
              .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
              .addGap(20, 20, 20)
              .addComponent(jLabel1)))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
    TelaPrincipal TelaDeMovimentacao = new TelaPrincipal();
    TelaDeMovimentacao.setVisible(true);
    dispose();
  }//GEN-LAST:event_jButtonVoltarActionPerformed

  private void jTextFieldveiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldveiculosActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldveiculosActionPerformed

  private void jTextFieldMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMovimentacaoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldMovimentacaoActionPerformed

  private void jTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldDataActionPerformed

  private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldValorActionPerformed

  private void jTextFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldDescricaoActionPerformed

  private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
    try {
      String nomeDespesaSelecionada = (String) jComboBoxDespesa.getSelectedItem();
      int idTipoDespesa = -1;

      if (jComboBoxDespesa.getSelectedIndex() <= 0) {
        JOptionPane.showMessageDialog(this, "Selecione um tipo de despesa!");
        return;
      }

      ArrayList<TipoDeDespesa> listaDespesas = tipoDao.listaDeTiposDeDespesas();
      for (TipoDeDespesa t : listaDespesas) {
        if (t.getDescricao().equalsIgnoreCase(nomeDespesaSelecionada)) {
          idTipoDespesa = t.getIdTipoDeDespesa();
          break;
        }
      }

      if (idTipoDespesa == -1) {
        JOptionPane.showMessageDialog(this, "Erro ao identificar o tipo de despesa.");
        return;
      }

      if ("CADASTRAR".equals(modo)) {
        String idMovStr = jTextFieldMovimentacao.getText().trim();
        String idVeicStr = jTextFieldveiculos.getText().trim();
        String data = jTextFieldData.getText().trim();
        String valorStr = jTextFieldValor.getText().trim().replace(",", ".");
        String descricao = jTextFieldDescricao.getText().trim();
        String statusSelecionado = String.valueOf(jComboBoxStatus.getSelectedItem());

        if (idVeicStr.isEmpty() || data.isEmpty() || valorStr.isEmpty() || descricao.isEmpty()) {
          JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
          return;
        }

        int idMov = Integer.parseInt(idMovStr);
        int idVeic = Integer.parseInt(idVeicStr);
        double valor = Double.parseDouble(valorStr);

        if (veicDao.buscarPorId(idVeic) == null) {
          JOptionPane.showMessageDialog(this, "Veículo não encontrado (ID " + idVeic + ").");
          return;
        }

        Movimentacao nova = new Movimentacao(idMov, idVeic, idTipoDespesa, descricao, data, valor, statusSelecionado);

        movDao.salvar(nova);

        carregarTabela();
        limparCampos();
        bloquearCampos();
        modo = "";
        JOptionPane.showMessageDialog(this, "Movimentação cadastrada com sucesso!");

      } else if ("EDITAR".equals(modo)) {
        String idMovStr = jTextFieldMovimentacao.getText().trim();
        if (idMovStr.isEmpty()) {
          JOptionPane.showMessageDialog(this, "Informe o ID da movimentação para atualizar.");
          return;
        }
        int idMov = Integer.parseInt(jTextFieldMovimentacao.getText());
        Movimentacao existente = movDao.buscarPorId(idMov);

        if (existente != null) {
          existente.setIdVeiculo(Integer.parseInt(jTextFieldveiculos.getText()));
          existente.setIdTipoDespesa(idTipoDespesa);
          existente.setData(jTextFieldData.getText());
          existente.setValor(Double.parseDouble(jTextFieldValor.getText().replace(",", ".")));
          existente.setDescricao(jTextFieldDescricao.getText());
          existente.setStatus((String) jComboBoxStatus.getSelectedItem());

          movDao.atualizar(existente);
          carregarTabela();
          limparCampos();
          bloquearCampos();
          modo = "";
          JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
        }
      }
    } catch (NumberFormatException nfe) {
      JOptionPane.showMessageDialog(this, "Verifique os valores numéricos (Valor ou ID Veículo).");
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
      e.printStackTrace();
    }
  }//GEN-LAST:event_jButtonConfirmarActionPerformed

  private void jButtonCadastrarMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {
    modo = "CADASTRAR";
    limparCampos();
    liberarCampos();

    int novoId = gerarProximoId();
    jTextFieldMovimentacao.setText(String.valueOf(novoId));
  }//GEN-LAST:event_jButtonCadastrarMovimentacaoActionPerformed

  private void jButtonGerenciarMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarMovimentacaoActionPerformed
    try {
      String idStr = JOptionPane.showInputDialog(this, "Digite o ID da movimentação para carregar:");
      if (idStr == null || idStr.trim().isEmpty()) return;
      int id = Integer.parseInt(idStr.trim());

      Movimentacao m = movDao.buscarPorId(id);
      if (m == null) {
        JOptionPane.showMessageDialog(this, "Movimentação não encontrada.");
        return;
      }

      try {
        TipoDeDespesa t = tipoDao.buscarPorId(m.getIdTipoDespesa());
        if (t != null) {
          jComboBoxDespesa.setSelectedItem(t.getDescricao());
        }
      } catch (Exception e) {
        System.out.println("Erro ao setar combo: " + e.getMessage());
      }

      jTextFieldMovimentacao.setText(String.valueOf(m.getIdMovimentacao()));
      jTextFieldveiculos.setText(String.valueOf(m.getIdVeiculo()));
      jTextFieldData.setText(m.getData());
      jTextFieldValor.setText(String.valueOf(m.getValor()));
      jTextFieldDescricao.setText(m.getDescricao());
      jComboBoxStatus.setSelectedIndex(0);

      modo = "EDITAR";

      jTextFieldMovimentacao.setEditable(false);
      jTextFieldveiculos.setEditable(true);
      jComboBoxDespesa.setEnabled(true);

      jTextFieldData.setEditable(true);
      jTextFieldValor.setEditable(true);
      jTextFieldDescricao.setEditable(true);
      jComboBoxStatus.setEnabled(true);

      JOptionPane.showMessageDialog(this, "Movimentação carregada.");
    } catch (NumberFormatException nfe) {
      JOptionPane.showMessageDialog(this, "ID inválido.");
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, "Erro ao buscar movimentação: " + e.getMessage());
    }
  }//GEN-LAST:event_jButtonGerenciarMovimentacaoActionPerformed

  private void jButtonRemoverMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverMovimentacaoActionPerformed
    try {
      String idStr = JOptionPane.showInputDialog(this, "Digite o ID da movimentação que deseja remover:");
      if (idStr == null || idStr.trim().isEmpty()) return;
      int id = Integer.parseInt(idStr.trim());

      Movimentacao m = movDao.buscarPorId(id);
      if (m == null) {
        JOptionPane.showMessageDialog(this, "Movimentação não encontrada.");
        return;
      }

      int confirm = JOptionPane.showConfirmDialog(this, "Remover movimentação ID " + id + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
      if (confirm == JOptionPane.YES_OPTION) {
        movDao.remover(id);
        carregarTabela();
        limparCampos();
        bloquearCampos();
        modo = "";
        JOptionPane.showMessageDialog(this, "Movimentação removida.");
      }
    } catch (NumberFormatException nfe) {
      JOptionPane.showMessageDialog(this, "ID inválido.");
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, "Erro ao remover: " + e.getMessage());
    }
  }//GEN-LAST:event_jButtonRemoverMovimentacaoActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new TelaDeMovimentacao().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonCadastrarMovimentacao;
  private javax.swing.JButton jButtonConfirmar;
  private javax.swing.JButton jButtonGerenciarMovimentacao;
  private javax.swing.JButton jButtonRemoverMovimentacao;
  private javax.swing.JButton jButtonVoltar;
  private javax.swing.JComboBox<String> jComboBoxStatus;
  private javax.swing.JEditorPane jEditorPane1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollBar jScrollBar1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable jTable1;
  private javax.swing.JTextField jTextFieldData;
  private javax.swing.JTextField jTextFieldDescricao;
  private javax.swing.JComboBox<String> jComboBoxDespesa;
  private javax.swing.JTextField jTextFieldMovimentacao;
  private javax.swing.JTextField jTextFieldValor;
  private javax.swing.JTextField jTextFieldveiculos;
  // End of variables declaration//GEN-END:variables
}
