/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controllers.TipoDeDespesasController;
import modelos.classes.TipoDeDespesa;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class TelaRegistroDeDespesas extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRegistroDeDespesas.class.getName());

  private String modo = "";
  private TipoDeDespesasController controller;
  private int idSelecionado = -1;

  /**
   * Creates new form TelaRegistroDeDespesas
   */
  public TelaRegistroDeDespesas() {
    initComponents();
    controller = new TipoDeDespesasController();
    carregarTabela();
    this.setLocationRelativeTo(null);
    jTextArea1.setEnabled(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSlider1 = new javax.swing.JSlider();
    jScrollBar1 = new javax.swing.JScrollBar();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTree1 = new javax.swing.JTree();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jButtonVoltar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTableGreedDespesas = new javax.swing.JTable();
    jButtonAtualizarDespesa = new javax.swing.JButton();
    jLabel10 = new javax.swing.JLabel();
    jButtonConfirmar = new javax.swing.JButton();
    jButtonCadastrarDespesa = new javax.swing.JButton();
    jButtonListarDespesa = new javax.swing.JButton();
    jButtonRemoverDespesa = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();

    jScrollPane3.setViewportView(jTree1);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(31, 146, 126));

    jPanel2.setBackground(new java.awt.Color(16, 58, 83));

    jButtonVoltar.setBackground(new java.awt.Color(16, 58, 83));
    jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/botao-voltar.png"))); // NOI18N
    jButtonVoltar.setBorder(null);
    jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonVoltarActionPerformed(evt);
      }
    });

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    jTableGreedDespesas.setModel(new javax.swing.table.DefaultTableModel(
      new Object[][]{
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null}
      },
      new String[]{
        "ID Despesa", "Descrição"
      }
    ));
    jTableGreedDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTableGreedDespesasMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(jTableGreedDespesas);

    jButtonAtualizarDespesa.setText("Atualizar Despesas");
    jButtonAtualizarDespesa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonAtualizarDespesaActionPerformed(evt);
      }
    });

    jLabel10.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(255, 255, 255));
    jLabel10.setText("Descrição Despesa");

    jButtonConfirmar.setText("Confirmar");
    jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonConfirmarActionPerformed(evt);
      }
    });

    jButtonCadastrarDespesa.setText("Cadastrar Despesas");
    jButtonCadastrarDespesa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCadastrarDespesaActionPerformed(evt);
      }
    });

    jButtonListarDespesa.setText("Listar Despesas");
    jButtonListarDespesa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonListarDespesaActionPerformed(evt);
      }
    });

    jButtonRemoverDespesa.setText("Remover Despesas");
    jButtonRemoverDespesa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonRemoverDespesaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addGap(25, 25, 25)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(18, 18, 18)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addComponent(jButtonConfirmar)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jButtonVoltar)
              .addGap(13, 13, 13))
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGap(6, 6, 6)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAtualizarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrarDespesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonListarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoverDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
              .addContainerGap(125, Short.MAX_VALUE))))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
          .addContainerGap(97, Short.MAX_VALUE)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(38, 38, 38))
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonListarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonCadastrarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonRemoverDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonAtualizarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButtonVoltar)
                .addComponent(jButtonConfirmar))
              .addGap(15, 15, 15))))
    );

    jLabel2.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
    jLabel2.setText("GYNLOG");

    jLabel1.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
    jLabel1.setText("Controle de Frotas");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
          .addGap(14, 14, 14)
          .addComponent(jLabel2)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel1)
          .addContainerGap())
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
              .addGap(9, 9, 9)
              .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
              .addGap(18, 18, 18)
              .addComponent(jLabel1)))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
    TelaPrincipal TelaRegistroDeDespesas = new TelaPrincipal();
    TelaRegistroDeDespesas.setVisible(true);
    dispose();
  }//GEN-LAST:event_jButtonVoltarActionPerformed

  private void jButtonAtualizarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarDespesaActionPerformed
    // TODO add your handling code here:
    if (idSelecionado == -1) {
      JOptionPane.showMessageDialog(this, "Selecione uma despesa na tabela.");
      return;
    }

    String novaDescricao = jTextArea1.getText().trim();

    if (novaDescricao.isEmpty()) {
      JOptionPane.showMessageDialog(this, "Digite uma descrição para atualizar.");
      return;
    }

    String msg = controller.atualizarTipo(idSelecionado, novaDescricao);
    JOptionPane.showMessageDialog(this, msg);

    carregarTabela();
    limparCampos();
  }//GEN-LAST:event_jButtonAtualizarDespesaActionPerformed

  private void jButtonCadastrarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarDespesaActionPerformed
    modo = "CADASTRAR";
    jTextArea1.setEnabled(true);
    jTextArea1.setText("");
    idSelecionado = -1;
  }//GEN-LAST:event_jButtonCadastrarDespesaActionPerformed

  private void jButtonListarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarDespesaActionPerformed
    modo = "LISTAR";
  }//GEN-LAST:event_jButtonListarDespesaActionPerformed

  private void jButtonRemoverDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverDespesaActionPerformed
    if (idSelecionado == -1) {
      JOptionPane.showMessageDialog(this, "Selecione uma despesa.");
      return;
    }
    modo = "REMOVER";
  }//GEN-LAST:event_jButtonRemoverDespesaActionPerformed

  private void jTableGreedDespesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGreedDespesasMouseClicked
    // TODO add your handling code here:
    int linha = jTableGreedDespesas.getSelectedRow();
    idSelecionado = (int) jTableGreedDespesas.getValueAt(linha, 0);
    jTextArea1.setText(jTableGreedDespesas.getValueAt(linha, 1).toString());
  }//GEN-LAST:event_jTableGreedDespesasMouseClicked

  private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
    try {

      if (modo.equals("CADASTRAR")) {
        String desc = jTextArea1.getText().trim();
        if (desc.isEmpty()) {
          JOptionPane.showMessageDialog(this, "Digite uma descrição.");
          return;
        }
        JOptionPane.showMessageDialog(this, controller.cadastrarTipo(desc));
      } else if (modo.equals("ATUALIZAR")) {
        String desc = jTextArea1.getText().trim();
        if (idSelecionado == -1) {
          JOptionPane.showMessageDialog(this, "Selecione uma despesa.");
          return;
        }
        JOptionPane.showMessageDialog(this, controller.atualizarTipo(idSelecionado, desc));
      } else if (modo.equals("REMOVER")) {
        if (idSelecionado == -1) {
          JOptionPane.showMessageDialog(this, "Selecione uma despesa.");
          return;
        }
        JOptionPane.showMessageDialog(this, controller.removerTipo(idSelecionado));
      } else if (modo.equals("LISTAR")) {
        carregarTabela();
      } else {
        JOptionPane.showMessageDialog(this, "Escolha uma opção primeiro.");
        return;
      }

      carregarTabela();
      jTextArea1.setText("");
      jTextArea1.setEnabled(false);
      idSelecionado = -1;
      modo = "";

    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
    }
  }//GEN-LAST:event_jButtonConfirmarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new TelaRegistroDeDespesas().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAtualizarDespesa;
  private javax.swing.JButton jButtonCadastrarDespesa;
  private javax.swing.JButton jButtonConfirmar;
  private javax.swing.JButton jButtonListarDespesa;
  private javax.swing.JButton jButtonRemoverDespesa;
  private javax.swing.JButton jButtonVoltar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollBar jScrollBar1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JSlider jSlider1;
  private javax.swing.JTable jTableGreedDespesas;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTree jTree1;
  // End of variables declaration//GEN-END:variables

  private void carregarTabela() {
    try {
      List<TipoDeDespesa> lista = controller.listar();

      DefaultTableModel modelo = (DefaultTableModel) jTableGreedDespesas.getModel();
      modelo.setRowCount(0);

      for (TipoDeDespesa t : lista) {
        modelo.addRow(new Object[]{
          t.getIdTipoDeDespesa(),
          t.getDescricao()
        });
      }

    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Erro ao carregar tabela: " + e.getMessage());
    }
  }

  private void limparCampos() {
    jTextArea1.setText("");
    idSelecionado = -1;
    jTableGreedDespesas.clearSelection();
  }
}

