/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import modelos.classes.STATUS;
import modelos.classes.Veiculo;
import persistencia.VeiculosDAO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

public class TelaControleDeVeiculo extends javax.swing.JFrame {

  private VeiculosDAO dao = new VeiculosDAO();
  private String modo = "";

  public TelaControleDeVeiculo() {
    initComponents();
    setLocationRelativeTo(null);
    carregarTabela();
    bloquearCampos();
  }

  private void bloquearCampos() {
    jTextFieldIdVeiculo.setEditable(false);
    jTextFieldModelo.setEditable(false);
    jTextFieldPlaca.setEditable(false);
    jTextFieldAnoFabricacao.setEditable(false);
    jTextFieldMarca.setEditable(false);
    jComboBox1.setEnabled(false);
  }

  private void liberarCampos() {
    jTextFieldIdVeiculo.setEditable(true);
    jTextFieldModelo.setEditable(true);
    jTextFieldPlaca.setEditable(true);
    jTextFieldAnoFabricacao.setEditable(true);
    jTextFieldMarca.setEditable(true);
    jComboBox1.setEnabled(true);
  }

  private void limparCampos() {
    jTextFieldIdVeiculo.setText("");
    jTextFieldModelo.setText("");
    jTextFieldPlaca.setText("");
    jTextFieldAnoFabricacao.setText("");
    jTextFieldMarca.setText("");
    jComboBox1.setSelectedIndex(0);
  }

  private void carregarTabela() {
    try {
      ArrayList<Veiculo> lista = dao.listaDeVeiculos();

      DefaultTableModel modelo = (DefaultTableModel) jTableGreedVeiculos.getModel();
      modelo.setRowCount(0);

      for (Veiculo obj : lista) {
        modelo.addRow(new Object[]{
          obj.getIdVeiculo(),
          obj.getMarca(),
          obj.getModelo(),
          obj.getPlaca(),
          obj.getAnoFabricacao(),
          obj.getStatus()
        });
      }
    } catch (Exception e) {
      System.out.println("Erro ao carregar tabela: " + e.getMessage());
    }
  }

  private void filtrarTabela() {
    try {
      ArrayList<Veiculo> lista = dao.listaDeVeiculos();

      DefaultTableModel modeloTabela = (DefaultTableModel) jTableGreedVeiculos.getModel();
      modeloTabela.setRowCount(0);

      String marcaFiltro = jTextFieldMarca.getText().trim().toLowerCase();
      String modeloFiltro = jTextFieldModelo.getText().trim().toLowerCase();
      String anoFiltro = jTextFieldAnoFabricacao.getText().trim();
      int statusIndex = jComboBox1.getSelectedIndex();

      for (Veiculo obj : lista) {
        boolean combina = true;

        if (!marcaFiltro.equals("") && !obj.getMarca().toLowerCase().contains(marcaFiltro)) {
          combina = false;
        }
        if (!modeloFiltro.equals("") && !obj.getModelo().toLowerCase().contains(modeloFiltro)) {
          combina = false;
        }
        if (!anoFiltro.equals("")) {
          if (!String.valueOf(obj.getAnoFabricacao()).contains(anoFiltro)) {
            combina = false;
          }
        }

        if (statusIndex == 0) {
          if (!obj.getStatus().toString().equalsIgnoreCase("ATIVO")) {
            combina = false;
          }
        } else if (statusIndex == 1) {
          if (!obj.getStatus().toString().equalsIgnoreCase("INATIVO")) {
            combina = false;
          }
        }

        if (combina) {
          modeloTabela.addRow(new Object[]{
            obj.getIdVeiculo(),
            obj.getMarca(),
            obj.getModelo(),
            obj.getPlaca(),
            obj.getAnoFabricacao(),
            obj.getStatus()
          });
        }
      }

    } catch (Exception e) {
      System.out.println("Erro ao filtrar tabela: " + e.getMessage());
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    buttonGroup1 = new javax.swing.ButtonGroup();
    jScrollPane2 = new javax.swing.JScrollPane();
    jEditorPane1 = new javax.swing.JEditorPane();
    jPasswordField1 = new javax.swing.JPasswordField();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jButtonVoltar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTableGreedVeiculos = new javax.swing.JTable();
    jButtonCadastrarVeiculos = new javax.swing.JButton();
    jButtonConsultarVeiculo = new javax.swing.JButton();
    jButtonGerenciarVeiculo = new javax.swing.JButton();
    jTextFieldIdVeiculo = new javax.swing.JTextField();
    jComboBox1 = new javax.swing.JComboBox<>();
    jTextFieldMarca = new javax.swing.JTextField();
    jTextFieldModelo = new javax.swing.JTextField();
    jTextFieldPlaca = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jTextFieldAnoFabricacao = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    jButtonConfirmar = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();

    jLabel2.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
    jLabel2.setText("GYNLOG");

    jLabel3.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
    jLabel3.setText("GYNLOG");

    jLabel6.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
    jLabel6.setText("Controle de Frotas");

    jScrollPane2.setViewportView(jEditorPane1);

    jPasswordField1.setText("jPasswordField1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(31, 146, 126));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N

    jPanel2.setBackground(new java.awt.Color(16, 58, 83));

    jButtonVoltar.setBackground(new java.awt.Color(16, 58, 83));
    jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/botao-voltar.png"))); // NOI18N
    jButtonVoltar.setBorder(null);
    jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonVoltarActionPerformed(evt);
      }
    });

    jTableGreedVeiculos.setModel(new javax.swing.table.DefaultTableModel(
      new Object[][]{
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null}
      },
      new String[]{
        "IdVeiculo", "Marca", "Modelo", "Placa", "Ano de Fabricação", "Status"
      }
    ));
    jTableGreedVeiculos.addAncestorListener(new javax.swing.event.AncestorListener() {
      public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
        jTableGreedVeiculosAncestorAdded(evt);
      }

      public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
      }

      public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
      }
    });
    jTableGreedVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTableGreedVeiculosMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(jTableGreedVeiculos);

    jButtonCadastrarVeiculos.setText("Cadastrar veiculo");
    jButtonCadastrarVeiculos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCadastrarVeiculosActionPerformed(evt);
      }
    });

    jButtonConsultarVeiculo.setText("Consultar Veiculo");
    jButtonConsultarVeiculo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonConsultarVeiculoActionPerformed(evt);
      }
    });

    jButtonGerenciarVeiculo.setText("Gerenciar Veiculo");
    jButtonGerenciarVeiculo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonGerenciarVeiculoActionPerformed(evt);
      }
    });

    jTextFieldIdVeiculo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldIdVeiculoActionPerformed(evt);
      }
    });

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Ativo", "Inativo", " ", " "}));

    jTextFieldModelo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldModeloActionPerformed(evt);
      }
    });

    jLabel8.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("Status");

    jLabel9.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(255, 255, 255));
    jLabel9.setText("ID Veiculo");

    jLabel10.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(255, 255, 255));
    jLabel10.setText("Marca");

    jLabel11.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(255, 255, 255));
    jLabel11.setText("Modelo");

    jLabel12.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(255, 255, 255));
    jLabel12.setText("Placa");

    jLabel13.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
    jLabel13.setForeground(new java.awt.Color(255, 255, 255));
    jLabel13.setText("Ano de Fabricação");

    jButtonConfirmar.setText("Confirmar");
    jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonConfirmarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addGap(37, 37, 37)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addComponent(jButtonCadastrarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(28, 28, 28)
              .addComponent(jButtonConsultarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(33, 33, 33)
              .addComponent(jButtonGerenciarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGap(312, 312, 312)
                  .addComponent(jButtonVoltar))
                .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGap(29, 29, 29)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                          .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldIdVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                          .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGap(19, 19, 19)))
                      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                          .addComponent(jButtonConfirmar)
                          .addGap(25, 25, 25)))))))))
          .addContainerGap(64, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addGap(31, 31, 31)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jButtonCadastrarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonConsultarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonGerenciarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(60, 60, 60))
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addGap(29, 29, 29)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldIdVeiculo))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonConfirmar))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jButtonVoltar)
              .addGap(16, 16, 16))))
    );

    jLabel4.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
    jLabel4.setText("GYNLOG");

    jLabel7.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
    jLabel7.setText("Controle de Frotas");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addGap(16, 16, 16)
          .addComponent(jLabel4)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
              .addGap(142, 142, 142)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel7)
              .addGap(24, 24, 24))))
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addGap(20, 20, 20)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(jLabel1)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
    TelaPrincipal TelaControleDeveiculo = new TelaPrincipal();
    TelaControleDeveiculo.setVisible(true);
    dispose();
  }

  private void jButtonGerenciarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarVeiculoActionPerformed
    modo = "EDITAR";
    limparCampos();
    bloquearCampos();
    jTextFieldMarca.setEditable(true);
    jTextFieldModelo.setEditable(true);
    jTextFieldPlaca.setEditable(true);
    jTextFieldAnoFabricacao.setEditable(true);
    jComboBox1.setEnabled(true);
  }//GEN-LAST:event_jButtonGerenciarVeiculoActionPerformed

  private void jTextFieldIdVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdVeiculoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldIdVeiculoActionPerformed

  private void jTextFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldModeloActionPerformed

  private void jButtonCadastrarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarVeiculosActionPerformed
    modo = "CADASTRAR";
    limparCampos();
    liberarCampos();
  }//GEN-LAST:event_jButtonCadastrarVeiculosActionPerformed

  private void jButtonConsultarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarVeiculoActionPerformed

    if ("CONSULTAR".equals(modo)) {
      modo = "";
      limparCampos();
      bloquearCampos();
      carregarTabela();
    } else {
      modo = "CONSULTAR";
      limparCampos();


      jTextFieldModelo.setEditable(true);
      jTextFieldMarca.setEditable(true);
      jTextFieldAnoFabricacao.setEditable(true);
      jComboBox1.setEnabled(true);


      jTextFieldIdVeiculo.setEditable(false);
      jTextFieldPlaca.setEditable(false);
    }
  }

  private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {
    try {
      String statusString = jComboBox1.getSelectedItem().toString();
      STATUS statusEnum;
      try {
        statusEnum = STATUS.valueOf(statusString.trim().toUpperCase());
      } catch (IllegalArgumentException e) {
        statusEnum = STATUS.ATIVO;
      }

      if (modo.equals("CADASTRAR")) {
        int id = Integer.parseInt(jTextFieldIdVeiculo.getText());

        if (dao.idExiste(id)) {
          JOptionPane.showMessageDialog(null, "Erro: Já existe um veículo cadastrado com esse ID!");
          return;
        }

        String modelo = jTextFieldModelo.getText();
        String placa = jTextFieldPlaca.getText();
        int ano = Integer.parseInt(jTextFieldAnoFabricacao.getText());
        String marca = jTextFieldMarca.getText();

        Veiculo obj = new Veiculo(id, placa, marca, modelo, ano, statusEnum);
        dao.salvar(obj);

        carregarTabela();
        limparCampos();
        bloquearCampos();
      } else if (modo.equals("CONSULTAR")) {
        filtrarTabela();
      } else if (modo.equals("EDITAR")) {
        int id = Integer.parseInt(jTextFieldIdVeiculo.getText());
        String modelo = jTextFieldModelo.getText();
        String placa = jTextFieldPlaca.getText();
        int ano = Integer.parseInt(jTextFieldAnoFabricacao.getText());
        String marca = jTextFieldMarca.getText();

        Veiculo obj = new Veiculo(id, placa, marca, modelo, ano, statusEnum);
        dao.atualizar(obj);

        carregarTabela();
        limparCampos();
        if (!modo.equals("CONSULTAR")) {
          bloquearCampos();
        }
      }

      if (!modo.equals("CONSULTAR")) {
        modo = "";
      }

    } catch (Exception e) {
      System.out.println("Erro ao confirmar: " + e.getMessage());
      e.printStackTrace();
    }
  }

  private void jTableGreedVeiculosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableGreedVeiculosAncestorAdded
    int row = jTableGreedVeiculos.getSelectedRow();
    if (row >= 0) {


      jTextFieldIdVeiculo.setText(jTableGreedVeiculos.getValueAt(row, 0).toString());
      jTextFieldMarca.setText(jTableGreedVeiculos.getValueAt(row, 1).toString());
      jTextFieldModelo.setText(jTableGreedVeiculos.getValueAt(row, 2).toString());
      jTextFieldPlaca.setText(jTableGreedVeiculos.getValueAt(row, 3).toString());
      jTextFieldAnoFabricacao.setText(jTableGreedVeiculos.getValueAt(row, 4).toString());
      jComboBox1.setSelectedItem(jTableGreedVeiculos.getValueAt(row, 5).toString());


      if ("EDITAR".equals(modo)) {
        jTextFieldIdVeiculo.setEditable(false);
        jTextFieldMarca.setEditable(true);
        jTextFieldModelo.setEditable(true);
        jTextFieldPlaca.setEditable(true);
        jTextFieldAnoFabricacao.setEditable(true);
        jComboBox1.setEnabled(true);
      } else {

        bloquearCampos();
      }
    }
  }//GEN-LAST:event_jTableGreedVeiculosAncestorAdded

  private void jTableGreedVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGreedVeiculosMouseClicked

    int row = jTableGreedVeiculos.getSelectedRow();
    if (row >= 0) {

      jTextFieldIdVeiculo.setText(jTableGreedVeiculos.getValueAt(row, 0).toString());
      jTextFieldMarca.setText(jTableGreedVeiculos.getValueAt(row, 1).toString());
      jTextFieldModelo.setText(jTableGreedVeiculos.getValueAt(row, 2).toString());
      jTextFieldPlaca.setText(jTableGreedVeiculos.getValueAt(row, 3).toString());
      jTextFieldAnoFabricacao.setText(jTableGreedVeiculos.getValueAt(row, 4).toString());
      jComboBox1.setSelectedItem(jTableGreedVeiculos.getValueAt(row, 5).toString());
    }
  }//GEN-LAST:event_jTableGreedVeiculosMouseClicked


  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TelaControleDeVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TelaControleDeVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TelaControleDeVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TelaControleDeVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TelaControleDeVeiculo().setVisible(true);
      }
    });
  }


  //GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JButton jButtonCadastrarVeiculos;
  private javax.swing.JButton jButtonConfirmar;
  private javax.swing.JButton jButtonConsultarVeiculo;
  private javax.swing.JButton jButtonGerenciarVeiculo;
  private javax.swing.JButton jButtonVoltar;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JEditorPane jEditorPane1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPasswordField jPasswordField1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable jTableGreedVeiculos;
  private javax.swing.JTextField jTextFieldAnoFabricacao;
  private javax.swing.JTextField jTextFieldIdVeiculo;
  private javax.swing.JTextField jTextFieldMarca;
  private javax.swing.JTextField jTextFieldModelo;
  private javax.swing.JTextField jTextFieldPlaca;
  // End of variables declaration//GEN-END:variables
}
